### ISSUE TITLE
請開一個 branch: practice1, 並將 railsbridge 裡的初探 Rails 做完

### ISSUE THREAD

**Issue by sdlong** [LesleySchwarz/railsbridge-1#1]
http://railsbridge-docs-zh-tw.herokuapp.com/%E5%88%9D%E6%8E%A2-rails/

不用做加分題, 並把該 branch push 上去, master 保持不變

**Comment by LesleySchwarz** [comment]
https://github.com/LesleySchwarz/railsbridge-1/pull/2

**Comment by sdlong** [comment]
大致上沒有問題，最後一個 commit 有個小建議，請修正，並弄成新的 commit push 上去, 謝謝

**Comment by LesleySchwarz** [comment]
已修正完畢！謝謝

**Comment by sdlong** [comment]
code ok
請把該 Pull request merge , 謝謝
