### ISSUE TITLE
實作 railsbridge 的初探 rails 加分題

### ISSUE THREAD

**Issue by sdlong** [LesleySchwarz/railsbridge-1#3]
1. 本機端切到 branch: master
2. 打 git pull origin master 確認本機端的 master 已更新 ( 把 pull request 的內容更新進去 )
3. 建一個新的 branch: practice2
4. 開始實作加分題

**Comment by LesleySchwarz** [comment]
完成加分題前兩項，加入about頁面失敗，最後有加入使用者認證系統，但是加分跟扣分按鈕：一個使用者只能投一次的限制沒有完成。
已完成：
- 加一個「扣分」按鈕，做的事跟加分按鈕相反。
- 根據投票分數排序
  請幫忙code review，pr: https://github.com/LesleySchwarz/railsbridge-1/pull/4
  麻煩了 謝謝。

**Comment by LesleySchwarz** [comment]
修正完成上次code review的地方。請您閒暇之餘在幫我看看，謝謝。

**Comment by sdlong** [comment]
code ok, 請 merge 進去 :D
